import Head from 'next/head';
import Image from 'next/image';
import styles from './home.module.css';

export default function HomeContainer() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Welcome, </h2>
        <a href="/dashboard">Go to dashboard</a>
      </main>
    </div>
  )
}
